CarRent/CarRent/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

CarRent/catalog/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('cars/', CarListView.as_view(), name='cars'),
    path('car/<slug:car_slug>/', CarDetailView.as_view(), name='car'),
    path('mycars/', LoanedCarsByUserListView.as_view(), name='my-orders'),
    path('cars_add/', cars_add, name="cars_add"),
    path('create_car/', create_car),
    path('delete_car/<int:id>/', delete_car),
    path('edit_car/<int:id>/', edit_car),
    path('instances_add/', instances_add, name="instances_add"),
    path('create_carinstance/', create_carinstance)
    # path('carinstance/create/', CarInstanceCreate.as_view(), name="car_instance_create"),
    # path('carinstances/update/<slug:slug>/', CarInstanceUpdate.as_view(), name="car_instance_update"),
    # path('carinstances/delete/<slug:slug>/', CarInstanceDelete.as_view(), name="car_instance_delete")
]

ProjectCarRent/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

CarRent/catalog/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False


class Category(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите категорию автомобиля",
                            verbose_name="Категория автомобиля")

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Client(models.Model):
    first_name = models.CharField(max_length=30,
                                  help_text="Введите имя клиента",
                                  verbose_name="Имя клиента")
    last_name = models.CharField(max_length=30,
                                 help_text="Введите фамилию клиента",
                                 verbose_name="Фамилия клиента")

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Condition(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Введите состояние автомобиля",
                            verbose_name="Состояние автомобиля")

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Введите страну производителя",
                            verbose_name="Страна производителя")

    class Meta:
        verbose_name_plural = "country"

    def __str__(self):
        return self.name


class Car(models.Model):
    title = models.CharField(max_length=50,
                             null=True,
                             help_text="Введите марку автомобиля",
                             verbose_name="Марка автомобиля")
    slug = models.SlugField(max_length=255,
                            unique=True,
                            db_index=True,
                            verbose_name="URL",
                            default=uuid.uuid1)
    model = models.CharField(max_length=50,
                             null=True,
                             help_text="Введите модель автомобиля",
                             verbose_name="Модель автомобиля")
    num = models.CharField(max_length=20, null=True,
                           help_text="Введите номер автомобиля в автопарке",
                           verbose_name="Номер автомобиля в парке")
    reg_number = models.CharField(max_length=20,
                                  help_text="Введите рег.номер автомобиля",
                                  verbose_name="Рег.номер автомобиля")
    category = models.ForeignKey('Category',
                                 on_delete=models.CASCADE,
                                 null=True,
                                 help_text="Выберите категорию автомобиля",
                                 verbose_name="Категория автомобиля")
    country = models.ForeignKey('Country',
                                on_delete=models.CASCADE,
                                null=True,
                                help_text="Выберите страну производства",
                                verbose_name="Страна производства")
    condition = models.ForeignKey('Condition',
                                  on_delete=models.CASCADE,
                                  null=True,
                                  help_text="Выберите состояние автомобиля",
                                  verbose_name="Состояние автомобиля")

    def get_absolute_url(self):
        return reverse('car', kwargs={'car_slug': self.slug})

    def __str__(self):
        return '%s %s %s' % (self.num, self.title, self.model)

    class Meta:
        ordering = ["num"]


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус автомобиля",
                            verbose_name="Статус автомобиля")

    class Meta:
        verbose_name_plural = "statuses"

    def __str__(self):
        return self.name


class CarInstance(models.Model):
    car = models.ForeignKey('Car',
                            on_delete=models.CASCADE,
                            null=True,
                            verbose_name="Автомобиль")
    slug = models.SlugField(max_length=255,
                            unique=True,
                            db_index=True,
                            verbose_name="URL",
                            default=uuid.uuid1)
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=False,
                               help_text="Изменить статус автомобиля",
                               verbose_name="Статус автомобиля")
    date_start = models.CharField(max_length=20, null=True, blank=True,
                                  help_text="Введите начало срока аренды",
                                  verbose_name="Дата начала статуса")
    date_back = models.CharField(max_length=20, null=True, blank=True,
                                 help_text="Введите конец срока аренды",
                                 verbose_name="Дата окончания статуса")
    client = models.ForeignKey('Client', on_delete=models.CASCADE,
                               null=True,
                               help_text="Выберите клиента",
                               verbose_name="Клиент")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Заказчик",
                                 help_text="Выберите клиента заказа")

    class Meta:
        ordering = ["date_back"]

    @property
    def is_overdue(self):
        if self.date_back and date.today() > self.date_back:
            return True
        return False

    def __str__(self):
        return '%s %s' % (self.car, self.status)

CarRent/catalog/forms.py
from django import  forms
import datetime
from django.forms import ModelForm
from .models import CarInstance, Car, Client, Status

class CarsForm(forms.Form):
    title = forms.CharField(label="Марка автомобиля")
    model = forms.CharField(label="Модель автомобиля")
    reg_number = forms.CharField(label="Регистрационный номер")

class InstancesForm(forms.Form):
    car = forms.ModelChoiceField(label="Автомобиль", queryset=Car.objects.all())
    status = forms.ModelChoiceField(label="Статус", queryset=Status.objects.all())
    date_start = forms.CharField(label="Дата нач.аренды", initial=datetime.date.today)
    date_back = forms.CharField(label="Дата завер.аренды", initial=datetime.date.today)
    client = forms.ModelChoiceField(label="Клиент", queryset=Client.objects.all())

# class CarInstanceModelForm(forms.Form):
#     class Meta:
#         model = CarInstance
#         fields = ['car', 'status', 'date_start', 'date_back', 'client']

CarRent/catalog/views.py
from django.shortcuts import render
from django.http import *
from .models import Car, Condition, Category, CarInstance, Status, Country, Client
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CarsForm, InstancesForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

def index(request):
    num_car = Car.objects.all().count()
    num_instance = CarInstance.objects.all().count()

    # Доступные автомобили
    num_instance_available = CarInstance.objects.filter(status__exact=2).count()

    # Количество посещений этого view
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html',
                  context={'num_car': num_car,
                           'num_instance': num_instance,
                           'num_instance_available': num_instance_available,
                           'num_visits': num_visits}
                  )


class CarListView(generic.ListView):
    model = Car
    paginate_by = 3

class CarDetailView(generic.DetailView):
    model = Car
    slug_url_kwarg = 'car_slug'
    context_object_name = 'car'

class LoanedCarsByUserListView(LoginRequiredMixin, generic.ListView):
    '''
    Класс для прелставления списка автомобилей,
    которые находятся в аренде у текущего пользователя.
    '''

    model = CarInstance
    template_name = 'catalog/carinstance_list_borrowed_user.html'
    paginate_by = 10

    def ger_queryset(self):
        return CarInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')

def cars_add(request):
    car = Car.objects.all()
    carsForm = CarsForm()
    return render(request, "catalog/cars_add.html",
                  {"form": carsForm, "car": car})

#Добавление автомобиля в бд
def create_car(request):
    if request.method == "POST":
        car = Car()
        car.title = request.POST.get("title")
        car.model = request.POST.get("model")
        car.reg_number = request.POST.get("reg_number")
        car.save()
        # Возвразаемся на предыдущую страницу
        return HttpResponseRedirect("/cars_add/")

#Удаление автомобиля
def delete_car(request, id):
    try:
        car = Car.objects.get(id=id)
        car.delete()
        return HttpResponseRedirect("/cars_add/")
    except:
        return HttpResponseNotFound("<h2> Автомобиль не найден</h2>")

#Изменение данных автомобиля
def edit_car(request, id):
    car = Car.objects.get(id=id)
    if request.method == "POST":
        car.title = request.POST.get("title")
        car.model = request.POST.get("model")
        car.reg_number = request.POST.get("reg_number")
        car.save()
        return HttpResponseRedirect("/cars_add/")
    else:
        return render(request, "catalog/edit_car.html", {"car": car})


# Релализация отображения заказов в виде формы

# Переход на страницу добавления заказа
def instances_add(request):
    carInstance = CarInstance.objects.all()
    instancesForm = InstancesForm()
    return render(request, "catalog/instances_add.html",
                  {"form": instancesForm, "carinstance": carInstance})

def create_carinstance(request):
    if request.method == "POST":
        carInstance = CarInstance()
        carInstance.car = Car(id=request.POST.get("car"))
        carInstance.status = Status(id=request.POST.get("status"))
        carInstance.date_start = request.POST.get("date_start")
        carInstance.date_back = request.POST.get("date_back")
        carInstance.client = Client(id=request.POST.get("client"))
        carInstance.save()
        # Возвразаемся на предыдущую страницу
        return HttpResponseRedirect("/instances_add/")



# Отображение в виде запроса
# class CarInstanceCreate(CreateView):
#     model = CarInstance
#     fields = "__all__"
#     exclude = ['slug']
#     success_url = reverse_lazy('car_instances')
#
# class CarInstanceUpdate(UpdateView):
#         model = CarInstance
#         fields = "__all__"
#         success_url = reverse_lazy('car_instances')
#
# class CarInstanceDelete(DeleteView):
#     model = CarInstance
#     success_url = reverse_lazy('car_instances')
#
# class CarInstanceListView(generic.ListView):
#     model = CarInstance
#     paginate_by = 3

CarRent/catalog/templates/catalog/car.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Название автомобиля: {{ car.title }}</h1>

    <p><strong>Рег.номер: {{ car.reg_number }}</strong></p>
    <p><strong>Номер в автопарке: {{ car.num }}</strong></p>
    <p><strong>Категория: {{ car.category }}</strong></p>
    <p><strong>Состояние: {{ car.condition }}</strong></p>

{% if car.photo %}
<p><img class="img-article-left" src="{{car.photo.url}}"></p>
{% endif %}

{% endblock %}

CarRent/catalog/templates/catalog/car_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Название автомобиля: {{ car.title }}</h1>
    <div style="margin-left: 20px;margin-top: 20px">
        <p><strong>Рег.номер: {{ car.reg_number }}</strong></p>
        <p><strong>Номер в автопарке: {{ car.num }}</strong></p>
        <p><strong>Категория: {{ car.category }}</strong></p>
        <p><strong>Состояние: {{ car.condition }}</strong></p>
    </div>

    <h4>Подробная информация о статусе автомобили в автопарке:</h4>
    <div style="margin-left: 20px;margin-top: 20px">
        {% for copy in car.carinstance_set.all %}
            <hr><p class="{% if copy.status == 1 %} text-success
                            {% elif copy.status == 2 %} text-danger
                            {% else %} text-warning
                            {% endif %}">
            {{ copy.get_status_display }}</p>
            <p><strong>Cтaтyc автомобиля:</strong> {{copy.status}}</p>
        {% endfor %}
    </div>
{% endblock %}

CarRent/catalog/templates/catalog/car_list.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="car_list">
        <h1>Список автомобилей в БД</h1>
            {% if car_list %}
        <ul>
            {% for car in car_list %}
            <li>
                <a href="{{ car.get_absolute_url }}">
                    {{ car.title }}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>В базе нет автомобилей</p>
        {% endif %}
    </div>
{% endblock %}

CarRent/catalog/templates/catalog/carinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<h1>
  Удаление заказа
</h1>
<p>Вы уверены что хотите удалить заказ: {{car}}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Да, удалить">
</form>
{% endblock %}

CarRent/catalog/templates/catalog/carinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}

CarRent/catalog/templates/catalog/carinstance_list.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="carinstance_list">
        <h1>Список заказов в БД</h1>
            {% if carinstance_list %}
        <ul>
            {% for car_instance in carinstance_list %}
            <li>
<!--                <a href="{{ car_instance.get_absolute_url }}">-->
                {{ car_instance.id }} {{ car_instance.client }}
<!--                </a>-->
                <a href="/carinstances/update/{{car_instance.slug}}">Изменить</a>
                <a href="/carinstances/delete/{{car_instance.slug}}">Удалить</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>В базе нет заказов</p>
        {% endif %}
    </div>
{% endblock %}

CarRent/catalog/templates/catalog/carinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Аренда автомобиля</h1>
    <div style="margin-right: 100px;margin-top: 20px">
        {% if carinstance_list %}
        <ul>
            {% for carinst in carinstance_list %}
            <li class="{% if carinst.is_overdue %} text-danger{% endif %}">

<!--            <a href="{% url 'car' carinst.car.pk %}"></a>-->
                {{ carinst.car.title }}
                (Дата окончания аренды: {{ carinst.date_back }})
            </li>
            {% endfor %}
        </ul>
    </div>

    {% else %}
        <p> Нет авто со статусом "Арендован" </p>
    {% endif %}
{% endblock %}

CarRent/catalog/templates/catalog/cars_add.html
{% extends "base_generic.html" %}

{% block content %}
    <h3> Список существующих автомобилей</h3>
    <table>
        <thead>
            <th>
                Id
            </th>
            <th>
                Марка
            </th>
            <th>
                Модель
            </th>
            <th>
                Рег.номер
            </th>
        </thead>

        {% if car %}
            {% for car in car.all %}
                <tr>
                    <td>{{car.id}}</td>
                    <td>{{car.title}}</td>
                    <td>{{car.model}}</td>
                    <td>{{car.reg_number}}</td>
                    <td><a href="/edit_car/{{car.id}}">Изменить</a>,
                        <a href="/delete_car/{{car.id}}">Удалить</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <p>В базе данных нет существующих автомобилей</p>
        {% endif %}
    </table>

    <h3>Добавить новый автомобиль</h3>
    <form method="POST" action="/create_car/">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}

CarRent/catalog/templates/catalog/edit_car.html
{% extends "base_generic.html" %}

{% block content %}
    <h3> Список существующих автомобилей</h3>
    <h4>{{car.title}} {{car.model}}</h4>

    <form method="POST">
        {% csrf_token %}
        <p>
            <label>Изменить марку автомобиля</label><br>
            <input type="text" name="title" value="{{car.title}}" />
        </p>
        <p>
            <label>Изменить модель автомобиля</label><br>
            <input type="text" name="model" value="{{car.model}}" />
        </p>
        <p>
            <label>Изменить рег.номер автомобиля</label><br>
            <input type="text" name="reg_number" value="{{car.reg_number}}" />
        </p>
        <input type="submit" value="Сохранить изменения">
    </form>
{% endblock %}

CarRent/catalog/templates/catalog/instances_add.html
{% extends "base_generic.html" %}

{% block content %}
    <h3> Список существующих заказов</h3>
    <table>
        <thead>
            <th>
                Id
            </th>
            <th>
                Автомобиль
            </th>
            <th>
                Статус
            </th>
            <th>
                Дата нач.аренды
            </th>
            <th>
                Дата завер.аренды
            </th>
            <th>
                Клиент
            </th>
        </thead>

        {% if carinstance %}
            {% for carinstance in carinstance.all %}
                <tr>
                    <td>{{carinstance.id}}</td>
                    <td>{{carinstance.car}}</td>
                    <td>{{carinstance.status}}</td>
                    <td>{{carinstance.date_start}}</td>
                    <td>{{carinstance.date_back}}</td>
                    <td>{{carinstance.client}}</td>
<!--                    <td><a href="/edit_car/{{car.id}}">Изменить</a>,-->
<!--                        <a href="/delete_car/{{car.id}}">Удалить</a></td>-->
                </tr>
            {% endfor %}
        {% else %}
            <p>В базе данных нет существующих заказов</p>
        {% endif %}
    </table>

    <h3>Добавить новый заказ</h3>
    <form method="POST" action="/create_carinstance/">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}